// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-GKUqtqWW4oao5GAQfjpAYpVlUfyOamM',
    appId: '1:858071540671:web:4bfd8911e880b0866e370a',
    messagingSenderId: '858071540671',
    projectId: 'landresourcemanagement-f89ac',
    authDomain: 'landresourcemanagement-f89ac.firebaseapp.com',
    storageBucket: 'landresourcemanagement-f89ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlIqmEbz4whOg25qOeZ7dRJYcD-6g_2g',
    appId: '1:858071540671:android:e0aa50f4b16691796e370a',
    messagingSenderId: '858071540671',
    projectId: 'landresourcemanagement-f89ac',
    storageBucket: 'landresourcemanagement-f89ac.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-GKUqtqWW4oao5GAQfjpAYpVlUfyOamM',
    appId: '1:858071540671:web:54c2670e9453c59e6e370a',
    messagingSenderId: '858071540671',
    projectId: 'landresourcemanagement-f89ac',
    authDomain: 'landresourcemanagement-f89ac.firebaseapp.com',
    storageBucket: 'landresourcemanagement-f89ac.firebasestorage.app',
  );

}